Todo/urls.py
from django.urls import path

from . import views


app_name = "todo"
urlpatterns = [
    path("", views.get_todo_lists, name="get_todo_lists"),
    path("add/", views.add_todo, name="add_todo"),
    path("delete/<int:pk>/", views.delete_todo, name="delete_todo"),
    path("change/<int:pk>/", views.change_todo_tatus, name="change_todo_tatus"),
]

TodoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('auth/', include("authentication.urls")),
    path('todo/', include("Todo.urls")),
    path('admin/', admin.site.urls),
]

authentication/urls.py
from django.urls import path

from . import views

app_name = "auth"
urlpatterns = [
    path("login/", views.login_user, name="login_user"),
    path("register/", views.register_user, name="register_user"),
    path("logout/", views.logout_user, name="logout_user"),
]

Todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length = 200, blank=False)
    is_compleated = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created"]


    def __str__(self):
        return self.content

authentication/models.py
from django.db import models

# Create your models here.

Todo/views.py
from django.shortcuts import render, redirect

from .models import Todo

from django.contrib.auth.decorators import login_required


# /todo/ # GET REQ
@login_required(login_url="auth:login_user")
def get_todo_lists(request):
    todos = Todo.objects.filter(host=request.user)
    context = {
        "username": request.user,
        "list": todos,
    }
    return render(request, "Todo/todos.html", context)


# /todo/add/ # POST REQ
@login_required(login_url="auth:login_user")
def add_todo(request):
    if request.POST.get('content') is not None:
        todo = Todo.objects.create(
            host=request.user,
            content=request.POST.get('content')
        )
        todo.save()
        return redirect('todo:get_todo_lists')



# /todo/delete/<int>/ # POST REQ
@login_required(login_url="auth:login_user")
def delete_todo(request, pk):
    todo = Todo.objects.get(id=pk)

    if request.method == 'POST':
        todo.delete()
        return redirect("todo:get_todo_lists")
    
    context={"todo": todo.content}
    return render(request, 'Todo/delete.html', context)

# /todo/change/<int>/ # POST REQ
@login_required(login_url="auth:login_user")
def change_todo_tatus(request, pk):
    if request.method == 'POST':
        todo = Todo.objects.get(id=pk)
        todo.is_compleated = not todo.is_compleated
        todo.save()
        return redirect("todo:get_todo_lists")

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# /auth/login/ # POST REQ
def login_user(request):
    if request.user.is_authenticated:
        return redirect("todo:get_todo_lists")

    elif request.method == "POST":
        username = request.POST.get("username").lower()
        password = request.POST.get("password")

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User does not exits")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("todo:get_todo_lists")
        else:
            messages.error(request, "Usernaem or password does not correct")

    return render(request, "authentication/login.html")


# /auth/register/ # POST REQ
def register_user(request):

    if request.method == "POST":
        username = request.POST.get("username").lower()
        email = request.POST.get("email").lower()
        password_1 = request.POST.get("password_1")
        password_2 = request.POST.get("password_2")
        
        if password_1 != password_2:
            messages.error(request, "Confirm password dosn't match")
        else:
            try:
                user = User.objects.create_user(username, email, password_1)
                user.save()
                login(request, user)
                return redirect('todo:get_todo_lists')
            except:
                messages.error(request, "this username is arredy taken")        
        

    return render(request, "authentication/register.html")

# /auth/logout/ # POST REQ
@login_required(login_url="auth:login_user")
def logout_user(request):
    logout(request)
    return redirect("auth:login_user")

Todo/templates/Todo/delete.html
{% extends "main.html" %} {% block content %}
<div class="container">
  <form method='POST'>
    {% csrf_token %}
  <p>do you sure to delete this Todo <b><< {{todo}} >></b></p>
  <input class="submit" type="submit" />
  </form>
</div>
{% endblock content %}

Todo/templates/Todo/todos.html
{% extends "main.html" %} {% block content %}
<div class="container">
  <h1>Todos</h1>
  <p>{{username}}</p>

  <form method="POST" action="{% url 'todo:add_todo' %}">
    {% csrf_token %}
    <div class="feald">
      <p class="label">Todo text</p>
      <input
        type="text"
        name="content"
        class="input"
        placeholder="Todo text"
        required
      />
    </div>

    <input type="submit" value="Push" class="submit" />
  </form>

  <table>
    <tr>
      <th>text</th>
      <th>is completed</th>
    </tr>
    {% for element in list %}
    <tr>
      <td>{{element.content}}</td>
      <td><form method='POST' action="{% url 'todo:change_todo_tatus' element.id %}">
        {% csrf_token %}
        <input type='submit' value="{{element.is_compleated}}" class='submit'/>
      </form></a></td>
      <td><a href="{% url 'todo:delete_todo' element.id %}">delete</a></td>
    </tr>
    {% endfor %}
  </table>

  <a href="{% url 'auth:logout_user' %}">Logout</a>
</div>
{% endblock content %}

authentication/templates/authentication/login.html
{% extends "main.html" %} {% block content %}
<div class="container">
  <ul>
    {% for message in messages %}
    <li class="error">{{message}}</li>
    {% endfor %}
  </ul>
  <form method="POST">
    {% csrf_token %}
    <div class="feald">
      <p class="label">Username</p>
      <input
        type="text"
        name="username"
        class="input"
        placeholder="Username"
        required
      />
    </div>
    <div class="feald">
      <p class="label">Password</p>
      <input
        type="password"
        name="password"
        class="input"
        placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
        required
      />
    </div>

    <input type="submit" value="Login" class="submit" />
    <a href="{% url 'auth:register_user' %}">Don't have accoutn</a>
  </form>
</div>
{% endblock content %}

authentication/templates/authentication/register.html
{% extends "main.html" %} {% block content %}
<div class="container">
  <ul>
    {% for message in messages %}
    <li class="error">{{message}}</li>
    {% endfor %}
  </ul>
  <form method="POST">
    {% csrf_token %}
    <div class="feald">
      <p class="label">Username</p>
      <input
        type="text"
        class="input"
        name="username"
        placeholder="Username"
        required
      />
    </div>
    <div class="feald">
      <p class="label">Email</p>
      <input
        type="email"
        class="input"
        name="email"
        placeholder="Email"
        required
      />
    </div>
    <div class="feald">
      <p class="label">Password</p>
      <input
        type="password"
        class="input"
        name="password_1"
        placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
        required
      />
    </div>
    <div class="feald">
      <p class="label">Conferm Password</p>
      <input
        type="password"
        class="input"
        name="password_2"
        placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
        required
      />
    </div>

    <input type="submit" value="Register" class="submit" />
    <a href="{% url 'auth:login_user' %}">I have accoutn</a>
  </form>
</div>
{% endblock content %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>ToDo</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>